[tools]
bun = "1.2.18"
go = "1.25.5"
node = "24.12.0"
python = "3.14.2"
ruby = "3.4.8"
rust = "1.92.0"
terraform = "1.13.0"

# go tools
"go:golang.org/x/tools/cmd/goimports" = "0.39.0"
"go:golang.org/x/tools/cmd/gonew" = "0.39.0"

# npm packages
"npm:renovate" = "41.173.1"
"npm:mmcp" = "0.6.2"
"npm:pnpm" = "10.26.0"
"npm:pinpm" = "0.4.1"
"npm:@google/gemini-cli" = "0.20.2"
"npm:@openai/codex" = "0.72.0"
"npm:@github/copilot" = "0.0.369"

# ruby gems
"gem:xvert" = "0.4.0"

# pipx packages
"pipx:git+https://github.com/koki-develop/git-aicommit.git" = "v0.11.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "terraform"]
