[tools]
bun = "1.2.18"
go = "1.25.3"
node = "24.11.0"
python = "3.14.0"
ruby = "3.4.7"
rust = "1.91.0"
terraform = "1.13.0"

# go tools
"go:golang.org/x/tools/cmd/goimports" = "0.38.0"
"go:golang.org/x/tools/cmd/gonew" = "0.38.0"

# npm packages
"npm:renovate" = "41.169.0"
"npm:mmcp" = "0.5.0"
"npm:pnpm" = "10.20.0"
"npm:pinpm" = "0.4.1"
"npm:@anthropic-ai/claude-code" = "2.0.31"
"npm:@google/gemini-cli" = "0.11.3"
"npm:@openai/codex" = "0.53.0"
"npm:@github/copilot" = "0.0.353"

# ruby gems
"gem:xvert" = "0.4.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "terraform"]
