[tools]
bun = "1.2.18"
go = "1.25.6"
node = "24.13.0"
python = "3.14.2"
ruby = "3.4.8"
rust = "1.93.0"
terraform = "1.13.0"

# npm packages
"npm:renovate" = "42.95.1"
"npm:mmcp" = "0.6.2"
"npm:pinpm" = "0.4.1"

# ruby gems
"gem:xvert" = "0.4.0"

# pipx packages
"pipx:git+https://github.com/koki-develop/git-aicommit.git" = "v0.14.1"

[settings]
experimental = true
hook_env.chpwd_only = true
idiomatic_version_file_enable_tools = ["node", "terraform"]
