[tools]
bun = "1.2.18"
go = "1.25.4"
node = "24.11.1"
python = "3.14.0"
ruby = "3.4.7"
rust = "1.91.1"
terraform = "1.13.0"

# go tools
"go:golang.org/x/tools/cmd/goimports" = "0.39.0"
"go:golang.org/x/tools/cmd/gonew" = "0.39.0"

# npm packages
"npm:renovate" = "41.173.1"
"npm:mmcp" = "0.5.0"
"npm:pnpm" = "10.22.0"
"npm:pinpm" = "0.4.1"
"npm:@google/gemini-cli" = "0.14.0"
"npm:@openai/codex" = "0.57.0"
"npm:@github/copilot" = "0.0.356"

# ruby gems
"gem:xvert" = "0.4.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "terraform"]
